Neos:
  ContentRepository:
    Search:
      realtimeIndexing:
        enabled: false
      defaultConfigurationPerNodeType:
        '*':
          indexed: true
        'Flowpack.SimpleSearch.ContentRepositoryAdaptor:Type1':
          indexed: false

