
TYPO3:
  TYPO3CR:
    Search:
      defaultConfigurationPerType:
        references:
          indexing: '${''#'' + Array.join(Indexing.convertArrayOfNodesToArrayOfNodeIdentifiers(value), ''#'') + ''#''}'
      defaultContext:
        Json: Neos\Eel\Helper\JsonHelper
Neos:
  Neos:
    typoScript:
      autoInclude:
        Flowpack.SimpleSearch.ContentRepositoryAdaptor: true
