TYPO3:
  TYPO3CR:
    Search:
        date:
          indexing: "${(value ? value.format('U') : null)}"
        references:
          indexing: "${'#' + Array.join(Indexing.convertArrayOfNodesToArrayOfNodeIdentifiers(value), '#') + '#'}"
  Neos:
    typoScript:
      autoInclude:
        'Flowpack.SimpleSearch.ContentRepositoryAdaptor': TRUE