TYPO3:
  TYPO3CR:
    SearchCommons:
        date:
          indexing: "${(value ? value.format('U') : null)}"

  Neos:
    typoScript:
      autoInclude:
        'Flowpack.SimpleSearch.ContentRepositoryAdaptor': TRUE