
Neos:
  Neos:
    typoScript:
      autoInclude:
        Flowpack.SimpleSearch.ContentRepositoryAdaptor: true
  ContentRepository:
    Search:
      defaultConfigurationPerType:
        references:
          indexing: "${'#' + Array.join(Indexing.convertArrayOfNodesToArrayOfNodeIdentifiers(value), '#') + '#'}"
      defaultContext:
        Json: Neos\Eel\Helper\JsonHelper
